-- ============================================
-- Description:	Updates records in R2.Resource
-- =============================================
CREATE PROCEDURE R2.ResourceLoadUpdateLocal
AS
BEGIN
	update R2.ResourceLocal
	set
		[RESOURCE_ID] = l.[RESOURCE_ID]
		,[ACCOUNT_ID] = l.[ACCOUNT_ID]
		,[ISRC] = l.[ISRC]
		,[ARTIST_LIST] = l.[ARTIST_LIST]
		,[RESOURCE_LOCAL_ID] = l.[RESOURCE_LOCAL_ID]
		,[TITLE] = l.[TITLE]
		,[TITLE_OVERRIDE] = l.[TITLE_OVERRIDE]
		,[VERSION_TITLE] = l.[VERSION_TITLE]
		,[VERSION_TITLE_OVERRIDE] = l.[VERSION_TITLE_OVERRIDE]
		,[TITLE_EXTENSION] = l.[TITLE_EXTENSION]
		,[TITLE_EXTENSION_OVERRIDE] = l.[TITLE_EXTENSION_OVERRIDE]
		,[FORMATTED_TITLE] = l.[FORMATTED_TITLE]
		,[ARTIST_OVERRIDE] = l.[ARTIST_OVERRIDE]
		,[PC_NOTICE_YEAR] = l.[PC_NOTICE_YEAR]
		,[PC_NOTICE_COMPANY_ID] = l.[PC_NOTICE_COMPANY_ID]
		,[PC_NOTICE_COMPANY_NAME] = l.[PC_NOTICE_COMPANY_NAME]
		,[PC_NOTICE_EXTENSION] = l.[PC_NOTICE_EXTENSION]
		,[FORMATTED_PC_NOTICE] = l.[FORMATTED_PC_NOTICE]
		,[VERSION_TYPE] = l.[VERSION_TYPE]
		,[VERSION_TYPE_DESC] = l.[VERSION_TYPE_DESC]
		,[E_MARKETING_TAG] = l.[E_MARKETING_TAG]
		,[E_RELEASE_LABEL] = l.[E_RELEASE_LABEL]
		,[E_OWNING_LABEL] = l.[E_OWNING_LABEL]
		,[DESCRIPTION] = l.[DESCRIPTION]
		,[VIDEO_NETWORK] = l.[VIDEO_NETWORK]
		,[VIDEO_NETWORK_DESC] = l.[VIDEO_NETWORK_DESC]
		,[VIDEO_SEASON_ID] = l.[VIDEO_SEASON_ID]
		,[VIDEO_RELEASE_YEAR] = l.[VIDEO_RELEASE_YEAR]
		,[VIDEO_RATING] = l.[VIDEO_RATING]
		,[VIDEO_RATING_DESC] = l.[VIDEO_RATING_DESC]
		,[VIDEO_SHORT_DESCRIPTION] = l.[VIDEO_SHORT_DESCRIPTION]
		,[VIDEO_LONG_DESCRIPTION] = l.[VIDEO_LONG_DESCRIPTION]
		,[ASPECT_RATIO] = l.[ASPECT_RATIO]
		,[ASPECT_RATIO_DESC] = l.[ASPECT_RATIO_DESC]
		,[MOVIE_RATING] = l.[MOVIE_RATING]
		,[MOVIE_RATING_DESC] = l.[MOVIE_RATING_DESC]
		,[RATING_REASON] = l.[RATING_REASON]
		,[ORIGINAL_CATALOG_NUMBER] = l.[ORIGINAL_CATALOG_NUMBER]
		,[PREVIEW_START_TIME] = l.[PREVIEW_START_TIME]
		,[FORMATTED_PREVIEW_START_TIME] = l.[FORMATTED_PREVIEW_START_TIME]
		,[PREVIEW_START_TIME_FRACTION] = l.[PREVIEW_START_TIME_FRACTION]
		,[PREVIEW_STOP_TIME] = l.[PREVIEW_STOP_TIME]
		,[FORMATTED_PREVIEW_STOP_TIME] = l.[FORMATTED_PREVIEW_STOP_TIME]
		,[PREVIEW_STOP_TIME_FRACTION] = l.[PREVIEW_STOP_TIME_FRACTION]
		,[RESOURCE_COMPANY_LINK_ID] = l.[RESOURCE_COMPANY_LINK_ID]
		,[COUNTRY_ID] = l.[COUNTRY_ID]
		,[FAMILY_ID] = l.[FAMILY_ID]
		,[COMPANY_ID] = l.[COMPANY_ID]
		,[DIVISION_ID] = l.[DIVISION_ID]
		,[LABEL_ID] = l.[LABEL_ID]
		,[ORIGINATING_INDICATOR] = l.[ORIGINATING_INDICATOR]
		,[DQ_STATUS] = l.[DQ_STATUS]
		,[RIGHTS_TYPE] = l.[RIGHTS_TYPE]
		,[RIGHTS_TYPE_DESC] = l.[RIGHTS_TYPE_DESC]
		,[RIGHTS_OWNER_ID] = l.[RIGHTS_OWNER_ID]
		,[RIGHTS_OWNER_DESC] = l.[RIGHTS_OWNER_DESC]
		,[GENRE] = l.[GENRE]
		,[GENRE_DESC] = l.[GENRE_DESC]
		,[LOCAL_NOTES] = l.[LOCAL_NOTES]

		,CHANGE_CODE = ld.CHANGE_CODE 
		,CHANGE_DATE_TIME = getdate()
		,WORKFLOW_CODE = 'L'
	from 
		R2.ResourceLocal t
		inner join R2.LoadResourceLocal l 
			on t.[Resource_ID] = l.[Resource_ID] and t.[COMPANY_ID] = l.[COMPANY_ID] 
		inner join R2.LoadResourceLocalDriver ld 
			on l.[Resource_ID] = ld.[Resource_ID] and l.[COMPANY_ID] = ld.[COMPANY_ID] 
	where
		(ld.CHANGE_CODE = 'U' or ld.CHANGE_CODE = 'UD') and ld.[WORKFLOW_CODE] = 'T'
		and 
		l.[WORKFLOW_CODE] = 'LT'
		
	-- update row counts		
	exec R2.TransformLogTaskInsert 'R2.ResourceLocal', @@rowcount, 'U'
		
END
