CREATE PROCEDURE R2.ReleaseExtractLoadTrackLocalInsert
AS
insert into R2.LoadTrackLocal
select * from 
openquery (R2,
'
SELECT 
    TD.RELEASE_ID, 
    TD.TRACK_GROUP_ID, 
    TD.GROUP_TITLE, 
    TD.GROUP_VERSION_TITLE, 
    TD.GROUP_SEQUENCE_NO, 
    TD.GROUP_RESOURCE_GROUP_ID, 
    TD.TRACK_ID, 
    TD.SEQUENCE_NO, 
    TD.TRACK_RELEASE_INDICATOR, 
    TD.TRACK_TIME, 
    TD.FORMATTED_TRACK_TIME, 
    TD.PAUSE_TIME, 
    TD.FORMATTED_PAUSE_TIME, 
    TD.TRACK_ARTIST_LIST, 
    TD.TRACK_TITLE, 
    TD.TRACK_VERSION_TITLE, 
    TD.TRACK_TITLE_EXTENSION, 
    TD.FORMATTED_TRACK_TITLE, 
    TD.USE_VERSION_TITLE_INDICATOR, 
    TD.USE_TITLE_EXTENSION_INDICATOR, 
    TD.TRACK_ARTIST_OVERRIDE, 
    TD.TRACK_TITLE_OVERRIDE, 
    TD.TRACK_VERSION_TITLE_OVERRIDE, 
    TD.TRACK_TITLE_EXTENSION_OVERRIDE, 
    TD.RESOURCE_INDEX_GROUP_ID, 
    TD.MATRIX_ID, 
    TD.SOURCE_CATALOG_NUMBER, 
    TD.SOURCE_SEQUENCE_NO, 
    TD.GHOST_INDICATOR, 
    TD.IMAGE_RESOURCE_ID, 
    TD.IMAGE_ISRC, 
    TD.LICENSING_CREDIT, 
    TD.PRINT_MEDLEY_INDICATOR, 
    TD.TRACK_NOTES, 
    TD.TRACK_AVAILABLE_INDICATOR,
    TD.RESOURCE_ID, 
    TD.ACCOUNT_ID, 
    TD.ISRC, 
	TD.COUNTRY_ID, 
	TD.FAMILY_ID, 
	TD.COMPANY_ID, 
	TD.DIVISION_ID, 
	TD.LABEL_ID, 
	TD.ORIGINATING_COUNTRY_ID, 
	TD.ORIGINATING_FAMILY_ID, 
	TD.ORIGINATING_COMPANY_ID, 
	TD.ORIGINATING_DIVISION_ID, 
	TD.ORIGINATING_LABEL_ID, 
	TD.ORIGINATING_INDICATOR, 
	DK.ACTION_CODE CHANGE_CODE,
	DK.GENERIC_DATE CHANGE_DATE_TIME,
	''E'' WORKFLOW_CODE
FROM 
    IFE.TRACK_DETAIL TD, 
    PARTNER.DRIVER_KEY DK
WHERE 
    TD.ACCOUNT_ID = 0
    
    AND TD.RELEASE_ID = DK.UNIQUE_ID 
    AND TD.COMPANY_ID = DK.LOCAL_DESIGNATION_ID
    
    AND DK.REPERTOIRE_TYPE = ''PRODCT''
    AND DK.GENERIC_STRING = ''P''
')
;