CREATE TABLE [CTX].[DataRepertoire](
	[CONTRACT_ID] numeric (38, 0) NOT NULL,
	[REPERTOIRE_TYPE] [nvarchar](6) NOT NULL,
	[UNIQUE_ID] numeric (38, 0) NOT NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'I' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) NOT NULL DEFAULT ('L')
) ON [PRIMARY]