CREATE TABLE [R2].[TrackLocal](
	[RELEASE_ID] [numeric](38, 0) NOT NULL,
	[GROUP_SEQUENCE_NO] [numeric](38, 0) NULL,
	[TRACK_ID] [numeric](38, 0) NOT NULL,
	[SEQUENCE_NO] [numeric](38, 0) NULL,
	[TRACK_ARTIST_LIST] [nvarchar](max) NULL,
	[TRACK_TITLE] [nvarchar](max) NULL,
	[TRACK_VERSION_TITLE] [nvarchar](max) NULL,
	[TRACK_TITLE_EXTENSION] [nvarchar](max) NULL,
	[FORMATTED_TRACK_TITLE] [nvarchar](max) NULL,
	[RESOURCE_ID] [numeric](38, 0) NOT NULL,
	[ACCOUNT_ID] [numeric](38, 0) NOT NULL,
	[ISRC] [nvarchar](12) NULL,
	[COUNTRY_ID] [nvarchar](2) NOT NULL,
	[FAMILY_ID] [nvarchar](6) NULL,
	[COMPANY_ID] [nvarchar](6) NOT NULL,
	[DIVISION_ID] [nvarchar](6) NOT NULL,
	[LABEL_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_INDICATOR] [nvarchar](1) NOT NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'I' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) NOT NULL DEFAULT ('L')
) ON [PRIMARY]
