//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapTestConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BingResult
    {
        public int Id { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    
        public virtual TestItem TestItem { get; set; }
    }
}
