//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapTestConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapTestResult
    {
        public int id { get; set; }
        public Nullable<int> campId { get; set; }
        public Nullable<int> resellId { get; set; }
        public string address { get; set; }
        public string noZipAddress { get; set; }
        public string zipDisplay { get; set; }
        public Nullable<decimal> zipLongitude { get; set; }
        public Nullable<decimal> zipLatitude { get; set; }
        public string noZipDisplay { get; set; }
        public Nullable<decimal> noZipLongitude { get; set; }
        public Nullable<decimal> noZipLatitude { get; set; }
        public Nullable<decimal> distance { get; set; }
    }
}
