//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapTestConsole.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResultModelContainer : DbContext
    {
        public ResultModelContainer()
            : base("name=ResultModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TestItem> TestItems { get; set; }
        public DbSet<GoogleResult> GoogleResults { get; set; }
        public DbSet<OpenStreetResult> OpenStreetResults { get; set; }
        public DbSet<BingResult> BingResults { get; set; }
        public DbSet<TestResult> TestResults { get; set; }
        public DbSet<Vendors> Vendors { get; set; }
    }
}
