//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapTestConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorTestResult
    {
        public VendorTestResult()
        {
            this.DistanceResults = new HashSet<DistanceResult>();
            this.DistanceResults1 = new HashSet<DistanceResult>();
        }
    
        public int Id { get; set; }
        public int TestItemId { get; set; }
        public int VendorId { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
    
        public virtual TestItem TestItem { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<DistanceResult> DistanceResults { get; set; }
        public virtual ICollection<DistanceResult> DistanceResults1 { get; set; }
    }
}
