CREATE TABLE [R2].[LoadCompany](
	[COUNTRY_ID] [nvarchar](2) NOT NULL,
	[COMPANY_ID] [nvarchar](6) NOT NULL,
	[AUDIT_DATE_CREATED] [datetime] NOT NULL,
	[AUDIT_DATE_CHANGED] [datetime] NOT NULL,
	[AUDIT_EMPLOYEE_NO] [numeric](38, 0) NOT NULL,
	[STATUS] [nvarchar](1) NOT NULL,
	[LANGUAGE_NO] [numeric](38, 0) NULL,
	[NAME] [nvarchar](255) NOT NULL,
	[ADDRESS_1] [nvarchar](40) NULL,
	[ADDRESS_2] [nvarchar](30) NULL,
	[CITY] [nvarchar](20) NULL,
	[STATE] [nvarchar](50) NULL,
	[ZIP_CODE] [nvarchar](10) NULL,
	[FAMILY_ID] [nvarchar](6) NULL,
	[DATE_LAST_GT] [datetime] NULL,
	[RIGHTS_OWNER_ID] [numeric](38, 0) NULL,
	[UPC_AUTO_ALLOCATION_INDICATOR] [nvarchar](1) NOT NULL,
	[ISAC_COMPANY_CODE] [nvarchar](6) NULL,
	[UNIQUE_ID] [numeric](38, 0) NOT NULL,
	[ACCOUNT_ID] [numeric](38, 0) NOT NULL,
) ON [PRIMARY]
