CREATE TABLE [R2].[Track](
	[RELEASE_ID] [numeric](38, 0) NOT NULL,
	[TRACK_GROUP_ID] [numeric](38, 0) NOT NULL,
	[GROUP_TITLE] [nvarchar](max) NULL,
	[GROUP_VERSION_TITLE] [nvarchar](max) NULL,
	[GROUP_SEQUENCE_NO] [numeric](38, 0) NOT NULL,
	[GROUP_RESOURCE_GROUP_ID] [numeric](38, 0) NULL,
	[TRACK_ID] [numeric](38, 0) NOT NULL,
	[SEQUENCE_NO] [numeric](38, 0) NOT NULL,
	[TRACK_RELEASE_INDICATOR] [nvarchar](1) NOT NULL,
	[TRACK_TIME] [numeric](38, 0) NOT NULL,
	[FORMATTED_TRACK_TIME] [nvarchar](max) NULL,
	[PAUSE_TIME] [numeric](38, 0) NULL,
	[FORMATTED_PAUSE_TIME] [nvarchar](max) NULL,
	[USE_VERSION_TITLE_INDICATOR] [nvarchar](1) NOT NULL,
	[USE_TITLE_EXTENSION_INDICATOR] [nvarchar](1) NOT NULL,
	[TRACK_ARTIST_OVERRIDE] [nvarchar](max) NULL,
	[TRACK_TITLE_OVERRIDE] [nvarchar](max) NULL,
	[TRACK_VERSION_TITLE_OVERRIDE] [nvarchar](max) NULL,
	[TRACK_TITLE_EXTENSION_OVERRIDE] [nvarchar](max) NULL,
	[RESOURCE_INDEX_GROUP_ID] [numeric](38, 0) NULL,
	[MATRIX_ID] [nvarchar](max) NULL,
	[SOURCE_CATALOG_NUMBER] [nvarchar](max) NULL,
	[SOURCE_SEQUENCE_NO] [numeric](38, 0) NULL,
	[GHOST_INDICATOR] [nvarchar](1) NOT NULL,
	[IMAGE_RESOURCE_ID] [numeric](38, 0) NULL,
	[IMAGE_ISRC] [nvarchar](max) NULL,
	[LICENSING_CREDIT] [nvarchar](max) NULL,
	[PRINT_MEDLEY_INDICATOR] [nvarchar](1) NOT NULL,
	[TRACK_NOTES] [nvarchar](max) NULL,
	[TRACK_AVAILABLE_INDICATOR] [nvarchar](1) NOT NULL,
	[RESOURCE_ID] [numeric](38, 0) NOT NULL,
	[ACCOUNT_ID] [numeric](38, 0) NOT NULL,
	[ISRC] [nvarchar](12) NULL,
	[ORIGINATING_COUNTRY_ID] [nvarchar](2) NOT NULL,
	[ORIGINATING_FAMILY_ID] [nvarchar](6) NULL,
	[ORIGINATING_COMPANY_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_DIVISION_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_LABEL_ID] [nvarchar](6) NOT NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'I' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) NOT NULL DEFAULT ('L')
) ON [PRIMARY]