CREATE PROCEDURE R2.ResourceExtractLoadResourceExcerptInsertForParents
AS

insert into R2.LoadResourceExcerpt
select * from 
openquery (R2,
'
SELECT DISTINCT 
    R.RESOURCE_RESOURCE_LINK_ID, 
    R.PARENT_RESOURCE_ID, 
    R.PARENT_ISRC, 
    R.CHILD_RESOURCE_ID, 
    R.CHILD_ISRC, 
    R.EXCERPT_START_TIME, 
    R.EXCERPT_START_TIME_DISPLAY, 
    R.EXCERPT_DURATION, 
    R.EXCERPT_DURATION_DISPLAY, 
    R.EXCERPT_END_TIME, 
    R.EXCERPT_END_TIME_DISPLAY, 
    R.LINK_VERSION,
	DK.ACTION_CODE CHANGE_CODE,
    DK.GENERIC_DATE CHANGE_DATE_TIME,
    ''E'' WORKFLOW_CODE
FROM 
    IFE.RESOURCE_EXCERPTS R,
    PARTNER.DRIVER_KEY DK
WHERE 
    R.PARENT_RESOURCE_ID = DK.UNIQUE_ID 
    
    AND DK.REPERTOIRE_TYPE = ''RECORD''
    AND DK.GENERIC_STRING = ''P''
')
;