//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ReceiptSite.Models
{
    public partial class ImageBank
    {
        public ImageBank()
        {
            this.Receipts = new HashSet<Receipt>();
            this.Receipts1 = new HashSet<Receipt>();
        }
    
        public int Id { get; set; }
        public string ImageType { get; set; }
        public byte[] Image { get; set; }
        public string ImageFilePath { get; set; }
        public byte[] Thumbnail { get; set; }
        public string ThumbnailFilePath { get; set; }
    
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual ICollection<Receipt> Receipts1 { get; set; }
    }
    
}
