//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ReceiptSite.Models
{
    public partial class Receipt
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string TextData { get; set; }
        public Nullable<int> ReceiptImageId { get; set; }
        public Nullable<int> BlankImageId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ImageBank ImageBank { get; set; }
        public virtual ImageBank ImageBank1 { get; set; }
    }
    
}
