CREATE PROCEDURE R2.ResourceExtractLoadResourceMedleyInsertForChildren
AS

insert into R2.LoadResourceMedley
select * from 
openquery (R2,
'
SELECT DISTINCT 
	R.RESOURCE_RESOURCE_LINK_ID, 
	R.RESOURCE_ID, 
	R.CHILD_RESOURCE_ID, 
	R.SEQUENCE_NO, 
	R.PAUSE_TIME, 
	R.FORMATTED_PAUSE_TIME, 
	R.ISRC, 
	R.CHILD_ISRC,
	DK.ACTION_CODE CHANGE_CODE,
	DK.GENERIC_DATE CHANGE_DATE_TIME,
    ''E'' WORKFLOW_CODE
FROM 
	IFE.RESOURCE_MEDLEYS R,
	PARTNER.DRIVER_KEY DK
WHERE 
	R.CHILD_RESOURCE_ID = DK.UNIQUE_ID 
    
	AND DK.REPERTOIRE_TYPE = ''RECORD''
	AND DK.GENERIC_STRING = ''P''
')
;