CREATE TABLE R2.LoadReleaseLocal
(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RELEASE_ID] [numeric](38, 0) NOT NULL,
	[ACCOUNT_ID] [numeric](38, 0) NOT NULL,
	[UPC] [nvarchar](14) NULL,
	[CONTEXT_UPC] [nvarchar](14) NULL,
	[UPC_TYPE] [nvarchar](1) NULL,
	[UPC_AUTO_DATE] [datetime] NULL,
	[GRID] [nvarchar](18) NULL,
	[CONTEXT_RELEASE_ID] [numeric](38, 0) NULL,
	[CONTEXT_TYPE] [nvarchar](1) NULL,
	[ARTIST_LIST] [nvarchar](4000) NULL,
	[TOTAL_TRACKS] [numeric](38, 0) NULL,
	[TOTAL_TIME] [numeric](38, 0) NULL,
	[FORMATTED_TOTAL_TIME] [nvarchar](4000) NULL,
	[ORIGINAL_PROJECT_ID] [numeric](38, 0) NOT NULL,
	[CONFIG_ID] [nvarchar](6) NOT NULL,
	[CONFIG_DESC] [nvarchar](4000) NULL,
	[CONFIG_SCOPE] [nvarchar](4000) NULL,
	[UNIQUE_INDICATOR] [nvarchar](1) NOT NULL,
	[PACKAGE_INDICATOR] [nvarchar](1) NOT NULL,
	[SOUNDTRACK_INDICATOR] [nvarchar](1) NULL,
	[MUSIC_TYPE] [nvarchar](6) NOT NULL,
	[MUSIC_TYPE_DESC] [nvarchar](4000) NULL,
	[RELEASE_TYPE] [nvarchar](6) NOT NULL,
	[RELEASE_TYPE_DESC] [nvarchar](4000) NULL,
	[P_NOTICE_COMPILATION] [nvarchar](6) NULL,
	[P_NOTICE_COMPILATION_DESC] [nvarchar](4000) NULL,
	[PACKAGING_DEFINITION] [nvarchar](4000) NULL,
	[VIDEO_TYPE] [nvarchar](6) NULL,
	[VIDEO_TYPE_DESC] [nvarchar](4000) NULL,
	[NOTES] [nvarchar](4000) NULL,
	[MISCELLANEOUS_CREDITS] [nvarchar](4000) NULL,
	[CRA_PROJECT_ID] [nvarchar](30) NULL,
	[SEARCH_INFORMATION] [nvarchar](4000) NULL,
	[DIGITAL_FORMAT] [nvarchar](6) NULL,
	[DIGITAL_FORMAT_DESC] [nvarchar](4000) NULL,
	[THEMATIC_CATEGORY] [nvarchar](6) NULL,
	[THEMATIC_CATEGORY_DESC] [nvarchar](4000) NULL,
	[CLASSICAL_CATEGORY] [nvarchar](6) NULL,
	[CLASSICAL_CATEGORY_DESC] [nvarchar](4000) NULL,
	[CLASSICAL_SUBCATEGORY] [nvarchar](6) NULL,
	[CLASSICAL_SUBCATEGORY_DESC] [nvarchar](4000) NULL,
	[AVAILABILITY_OVERRIDE_REASON] [nvarchar](4000) NULL,
	[RELEASE_LOCAL_ID] [numeric](38, 0) NOT NULL,
	[TITLE] [nvarchar](4000) NULL,
	[TITLE_OVERRIDE] [nvarchar](4000) NULL,
	[VERSION_TITLE] [nvarchar](4000) NULL,
	[VERSION_TITLE_OVERRIDE] [nvarchar](4000) NULL,
	[FORMATTED_TITLE] [nvarchar](4000) NULL,
	[ARTIST_OVERRIDE] [nvarchar](4000) NULL,
	[VERSION_TYPE] [nvarchar](6) NOT NULL,
	[VERSION_TYPE_DESC] [nvarchar](4000) NULL,
	[P_NOTICE_YEAR] [nvarchar](4) NULL,
	[P_NOTICE_COMPANY_ID] [numeric](38, 0) NULL,
	[P_NOTICE_COMPANY_NAME] [nvarchar](4000) NULL,
	[P_NOTICE_EXTENSION] [nvarchar](4000) NULL,
	[FORMATTED_P_NOTICE] [nvarchar](4000) NULL,
	[C_NOTICE_YEAR] [nvarchar](4) NULL,
	[C_NOTICE_COMPANY_ID] [numeric](38, 0) NULL,
	[C_NOTICE_COMPANY_NAME] [nvarchar](4000) NULL,
	[C_NOTICE_EXTENSION] [nvarchar](4000) NULL,
	[FORMATTED_C_NOTICE] [nvarchar](4000) NULL,
	[SERIES_ID] [numeric](38, 0) NULL,
	[SERIES_TITLE] [nvarchar](4000) NULL,
	[VIDEO_NETWORK] [nvarchar](6) NULL,
	[VIDEO_NETWORK_DESC] [nvarchar](4000) NULL,
	[VIDEO_SEASON_ID] [nvarchar](4000) NULL,
	[VIDEO_ORIGINAL_RELEASE_YEAR] [nvarchar](4) NULL,
	[VIDEO_RATING] [nvarchar](6) NULL,
	[VIDEO_RATING_DESC] [nvarchar](4000) NULL,
	[VIDEO_SHORT_DESCRIPTION] [nvarchar](4000) NULL,
	[VIDEO_LONG_DESCRIPTION] [nvarchar](4000) NULL,
	[E_MARKETING_TAG] [nvarchar](4000) NULL,
	[E_RELEASE_LABEL] [nvarchar](4000) NULL,
	[NPSC] [nvarchar](8) NULL,
	[VOD_TYPE] [nvarchar](6) NULL,
	[VOD_TYPE_DESC] [nvarchar](4000) NULL,
	[RELEASE_COMPANY_LINK_ID] [numeric](38, 0) NOT NULL,
	[COUNTRY_ID] [nvarchar](2) NOT NULL,
	[FAMILY_ID] [nvarchar](6) NULL,
	[COMPANY_ID] [nvarchar](6) NOT NULL,
	[DIVISION_ID] [nvarchar](6) NOT NULL,
	[LABEL_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_COUNTRY_ID] [nvarchar](2) NOT NULL,
	[ORIGINATING_FAMILY_ID] [nvarchar](6) NULL,
	[ORIGINATING_COMPANY_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_DIVISION_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_LABEL_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_INDICATOR] [nvarchar](1) NOT NULL,
	[STATUS] [nvarchar](1) NOT NULL,
	[STATUS_DESC] [nvarchar](4000) NULL,
	[ISSUING_EMPLOYEE_NO] [numeric](38, 0) NULL,
	[ISSUING_EMPLOYEE_NAME] [nvarchar](4000) NULL,
	[ROYALTY_ADMIN] [nvarchar](6) NULL,
	[ROYALTY_ADMIN_DESC] [nvarchar](4000) NULL,
	[CATALOG_NUMBER] [nvarchar](4000) NULL,
	[GENRE] [nvarchar](6) NULL,
	[GENRE_DESC] [nvarchar](4000) NULL,
	[RELEASE_DATE_YEAR] [nvarchar](4) NULL,
	[RELEASE_DATE_MONTH] [nvarchar](2) NULL,
	[RELEASE_DATE_DAY] [nvarchar](2) NULL,
	[RELEASE_DATE_DISPLAY] [nvarchar](4000) NULL,
	[LOCAL_NOTES] [nvarchar](4000) NULL,
	[DQ_STATUS] [nvarchar](6) NOT NULL,
	[DQ_STATUS_DESC] [nvarchar](4000) NULL,
	[CHANGE_CODE] [varchar](2) NOT NULL,
	[CHANGE_DATE_TIME] [datetime] NULL,
	[WORKFLOW_CODE] [varchar](2) DEFAULT 'E' NOT NULL
) ON [PRIMARY]