CREATE TABLE [R2].[ReleaseResourceLink](
	[RELEASE_RESOURCE_LINK_ID] [numeric](38, 0) NOT NULL,
	[AUDIT_DATE_CREATED] [datetime] NOT NULL,
	[AUDIT_DATE_CHANGED] [datetime] NOT NULL,
	[AUDIT_EMPLOYEE_NO] [numeric](38, 0) NOT NULL,
	[RELEASE_ID] [numeric](38, 0) NOT NULL,
	[RESOURCE_ID] [numeric](38, 0) NOT NULL,
	[PRIMARY_INDICATOR] [nvarchar](1) NOT NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'I' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) NOT NULL DEFAULT ('L')
) ON [PRIMARY]