//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesMvcApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Method
    {
        public Method()
        {
            this.Params = new HashSet<Param>();
        }
    
        public int Id { get; set; }
        public string MethodName { get; set; }
        public int RemoteWebServiceId { get; set; }
    
        public virtual RemoteWebService RemoteWebService { get; set; }
        public virtual ICollection<Param> Params { get; set; }
    }
}
