CREATE TABLE [CRA].[LoadContractTerritoryLink](
	[LOAD_CONTRACT_TERRITORY_LINK_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TERRITORY_ID] [nvarchar](10) NULL,
	[CONTRIBUTOR_ID] [bigint] NULL,
	[GTA_COMPANY_ID] [nvarchar](10) NULL,
	[TERRITORY_TYPE] [nvarchar](10) NULL,
	[CREATION_DATETIME] [datetime] NULL,
	[MODIFICATION_DATETIME] [datetime] NULL,
 CONSTRAINT [PK_LoadContractTerritoryLink] PRIMARY KEY CLUSTERED 
(
	[LOAD_CONTRACT_TERRITORY_LINK_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
