CREATE TABLE [CRA].[Contract](
	[CONTRACT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CONTRIBUTOR_ID] [bigint] NULL,
	[CRCO_START_DATE] [datetime] NULL,
	[CRCO_END_DATE] [datetime] NULL,
	[CRCO_COMMENTS] [ntext] NULL,
	[GTA_COMPANY_ID_1] [nvarchar](10) NULL,
	[GTA_COMPANY_ID_2] [nvarchar](10) NULL,
	[CRCO_MASTER_IND] [char](1) NULL,
	[CRCO_NO_RIGHTS_IND] [char](1) NULL,
	[CRCO_UPDATED_DATE] [datetime] NULL,
	[CRCO_MULTI_ARTIST_IND] [char](1) NULL,
	[CRCO_CREATION_DATE] [datetime] NULL,
	[CRCO_CREATED_BY_CONTACT] [varchar](50) NULL,
	[CRCO_EXP_DATE] [datetime] NULL,
 CONSTRAINT [PK_CONTRACT] PRIMARY KEY CLUSTERED 
(
	[CONTRACT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) 