CREATE TABLE [CRA].[LoadArticleContract](
	[LOAD_ARTICLE_CONTRACT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CRAR_ID] [bigint] NULL,
	[GTA_COMPANY_ID] [nvarchar](10) NULL,
	[CONTRIBUTOR_ID] [bigint] NULL,
	[CREATION_DATETIME] [datetime] NULL,
	[NO_RIGHTS_IND] [char](1) NULL,
	[RMS_ID] [nvarchar](20) NULL,
	[PPC] [nvarchar](20) NULL,
 CONSTRAINT [PK_LoadArticleContract] PRIMARY KEY CLUSTERED 
(
	[LOAD_ARTICLE_CONTRACT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
