CREATE TABLE [R2].[LoadRelease](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RELEASE_ID] [numeric](38, 0) NOT NULL,
	[ACCOUNT_ID] [numeric](38, 0) NOT NULL,
	[UPC] [nvarchar](14) NULL,
	[CONTEXT_UPC] [nvarchar](14) NULL,
	[UPC_TYPE] [nvarchar](1) NULL,
	[UPC_AUTO_DATE] [datetime] NULL,
	[GRID] [nvarchar](18) NULL,
	[CONTEXT_RELEASE_ID] [numeric](38, 0) NULL,
	[CONTEXT_TYPE] [nvarchar](1) NULL,
	[TOTAL_TRACKS] [numeric](38, 0) NULL,
	[TOTAL_TIME] [numeric](38, 0) NULL,
	[FORMATTED_TOTAL_TIME] [nvarchar](max) NULL,
	[ORIGINAL_PROJECT_ID] [numeric](38, 0) NOT NULL,
	[CONFIG_ID] [nvarchar](6) NOT NULL,
	[CONFIG_DESC] [nvarchar](max) NULL,
	[CONFIG_SCOPE] [nvarchar](max) NULL,
	[UNIQUE_INDICATOR] [nvarchar](1) NOT NULL,
	[PACKAGE_INDICATOR] [nvarchar](1) NOT NULL,
	[SOUNDTRACK_INDICATOR] [nvarchar](1) NULL,
	[MUSIC_TYPE] [nvarchar](6) NOT NULL,
	[MUSIC_TYPE_DESC] [nvarchar](max) NULL,
	[RELEASE_TYPE_DESC] [nvarchar](max) NULL,
	[P_NOTICE_COMPILATION_DESC] [nvarchar](max) NULL,
	[PACKAGING_DEFINITION] [nvarchar](max) NULL,
	[VIDEO_TYPE] [nvarchar](6) NULL,
	[VIDEO_TYPE_DESC] [nvarchar](max) NULL,
	[NOTES] [nvarchar](max) NULL,
	[MISCELLANEOUS_CREDITS] [nvarchar](max) NULL,
	[CRA_PROJECT_ID] [nvarchar](30) NULL,
	[SEARCH_INFORMATION] [nvarchar](max) NULL,
	[DIGITAL_FORMAT] [nvarchar](6) NULL,
	[DIGITAL_FORMAT_DESC] [nvarchar](max) NULL,
	[THEMATIC_CATEGORY] [nvarchar](6) NULL,
	[THEMATIC_CATEGORY_DESC] [nvarchar](max) NULL,
	[CLASSICAL_CATEGORY] [nvarchar](6) NULL,
	[CLASSICAL_CATEGORY_DESC] [nvarchar](max) NULL,
	[CLASSICAL_SUBCATEGORY] [nvarchar](6) NULL,
	[CLASSICAL_SUBCATEGORY_DESC] [nvarchar](max) NULL,
	[AVAILABILITY_OVERRIDE_REASON] [nvarchar](max) NULL,
	[ORIGINATING_COUNTRY_ID] [nvarchar](2) NOT NULL,
	[ORIGINATING_FAMILY_ID] [nvarchar](6) NULL,
	[ORIGINATING_COMPANY_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_DIVISION_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_LABEL_ID] [nvarchar](6) NOT NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'I' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) DEFAULT 'E' NOT NULL
) ON [PRIMARY]

