CREATE TABLE [DRA].[EntityRightsPeriod]
(
	[ENTITY_CLEARANCE_SET_ID] [numeric](38, 0) NOT NULL,
	[RIGHTS_PERIOD_ID] [numeric](38, 0) NOT NULL,
	[EXPIRY_DATE] [datetime] NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'I' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) NOT NULL DEFAULT ('L')
) ON [PRIMARY]