CREATE TABLE [DRA].[LoadEntityClearanceSet]
(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ENTITY_CLEARANCE_SET_ID] [numeric](38, 0) NOT NULL,
	[RESOURCE_ID] [numeric](38, 0) NULL,
	[RELEASE_ID] [numeric](38, 0) NULL,
	[TERRITORIAL_RIGHTS_NOTES] [nvarchar](4000) NULL,
	[TERRITORIAL_RIGHTS_NOTES_FLAG] [nvarchar](1) NULL,
	[COMPANY_ID] [nvarchar](6) NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'C' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) DEFAULT 'E' NOT NULL
) ON [PRIMARY]

