CREATE TABLE [R2].[LoadResourceLocal](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RESOURCE_ID] [numeric](38, 0) NOT NULL,
	[ACCOUNT_ID] [numeric](38, 0) NOT NULL,
	[ISRC] [nvarchar](12) NULL,
	[RESOURCE_TYPE] [nvarchar](6) NOT NULL,
	[RESOURCE_TYPE_DESC] [nvarchar](4000) NULL,
	[ARTIST_LIST] [nvarchar](4000) NULL,
	[ORIGINAL_PROJECT_ID] [numeric](38, 0) NOT NULL,
	[TIME] [numeric](38, 0) NOT NULL,
	[FORMATTED_TIME] [nvarchar](4000) NULL,
	[MUSIC_TYPE] [nvarchar](6) NULL,
	[MUSIC_TYPE_DESC] [nvarchar](4000) NULL,
	[LANGUAGE_NO] [numeric](38, 0) NULL,
	[LANGUAGE_DESC] [nvarchar](4000) NULL,
	[MISCELLANEOUS_CREDITS] [nvarchar](4000) NULL,
	[SAMPLE_CREDITS] [nvarchar](4000) NULL,
	[TECHNICAL_FORMAT] [nvarchar](6) NULL,
	[TECHNICAL_FORMAT_DESC] [nvarchar](4000) NULL,
	[ANALOG_DIGITAL_CODE] [nvarchar](6) NULL,
	[ANALOG_DIGITAL_CODE_DESC] [nvarchar](4000) NULL,
	[SAMPLING_FREQUENCY] [nvarchar](6) NULL,
	[SAMPLING_FREQUENCY_DESC] [nvarchar](4000) NULL,
	[BIT_DEPTH] [nvarchar](6) NULL,
	[BIT_DEPTH_DESC] [nvarchar](4000) NULL,
	[SCORE_PUBLISHER_ID] [numeric](38, 0) NULL,
	[SCORE_PUBLISHER_DESC] [nvarchar](4000) NULL,
	[SEARCH_INFORMATION] [nvarchar](4000) NULL,
	[SESSION_NAME] [nvarchar](4000) NULL,
	[SESSION_COUNTRY_ID] [nvarchar](2) NULL,
	[SESSION_COUNTRY_NAME] [nvarchar](4000) NULL,
	[SESSION_LOCATION_ID] [numeric](38, 0) NULL,
	[SESSION_LOCATION_DESC] [nvarchar](4000) NULL,
	[SESSION_SETTING] [nvarchar](6) NULL,
	[SESSION_SETTING_DESC] [nvarchar](4000) NULL,
	[SESSION_UNION_TYPE] [nvarchar](6) NULL,
	[SESSION_UNION_TYPE_DESC] [nvarchar](4000) NULL,
	[SESSION_PERFORMANCE_TYPE] [nvarchar](6) NULL,
	[SESSION_PERFORMANCE_TYPE_DESC] [nvarchar](4000) NULL,
	[SESSION_START_DATE_YEAR] [nvarchar](4) NULL,
	[SESSION_START_DATE_MONTH] [nvarchar](2) NULL,
	[SESSION_START_DATE_DAY] [nvarchar](2) NULL,
	[SESSION_START_DATE] [nvarchar](4000) NULL,
	[SESSION_END_DATE_YEAR] [nvarchar](4) NULL,
	[SESSION_END_DATE_MONTH] [nvarchar](2) NULL,
	[SESSION_END_DATE_DAY] [nvarchar](2) NULL,
	[SESSION_END_DATE] [nvarchar](4000) NULL,
	[ORIGINAL_MATRIX_NUMBER] [nvarchar](4000) NULL,
	[MASTERING_TRACK_COUNT] [numeric](38, 0) NULL,
	[CATEGORY] [nvarchar](6) NULL,
	[CATEGORY_DESC] [nvarchar](4000) NULL,
	[FORMAT] [nvarchar](6) NULL,
	[FORMAT_DESC] [nvarchar](4000) NULL,
	[COLOR_MODE] [nvarchar](6) NULL,
	[COLOR_MODE_DESC] [nvarchar](4000) NULL,
	[RESOLUTION] [nvarchar](6) NULL,
	[RESOLUTION_DESC] [nvarchar](4000) NULL,
	[MEASUREMENT] [nvarchar](6) NULL,
	[MEASUREMENT_DESC] [nvarchar](4000) NULL,
	[HEIGHT] [numeric](38, 0) NULL,
	[WIDTH] [numeric](38, 0) NULL,
	[VIDEO_TYPE] [nvarchar](6) NULL,
	[VIDEO_TYPE_DESC] [nvarchar](4000) NULL,
	[VIDEO_PRODUCTION_NUMBER] [nvarchar](4000) NULL,
	[NOTES] [nvarchar](4000) NULL,
	[ISAN] [nvarchar](4000) NULL,
	[AVAILABLE_INDICATOR] [nvarchar](1) NOT NULL,
	[RESOURCE_LOCAL_ID] [numeric](38, 0) NOT NULL,
	[TITLE] [nvarchar](4000) NULL,
	[TITLE_OVERRIDE] [nvarchar](4000) NULL,
	[VERSION_TITLE] [nvarchar](4000) NULL,
	[VERSION_TITLE_OVERRIDE] [nvarchar](4000) NULL,
	[TITLE_EXTENSION] [nvarchar](4000) NULL,
	[TITLE_EXTENSION_OVERRIDE] [nvarchar](4000) NULL,
	[FORMATTED_TITLE] [nvarchar](4000) NULL,
	[ARTIST_OVERRIDE] [nvarchar](4000) NULL,
	[PC_NOTICE_YEAR] [nvarchar](4) NULL,
	[PC_NOTICE_COMPANY_ID] [numeric](38, 0) NULL,
	[PC_NOTICE_COMPANY_NAME] [nvarchar](4000) NULL,
	[PC_NOTICE_EXTENSION] [nvarchar](4000) NULL,
	[FORMATTED_PC_NOTICE] [nvarchar](4000) NULL,
	[VERSION_TYPE] [nvarchar](6) NULL,
	[VERSION_TYPE_DESC] [nvarchar](4000) NULL,
	[E_MARKETING_TAG] [nvarchar](4000) NULL,
	[E_RELEASE_LABEL] [nvarchar](4000) NULL,
	[E_OWNING_LABEL] [nvarchar](4000) NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[VIDEO_NETWORK] [nvarchar](6) NULL,
	[VIDEO_NETWORK_DESC] [nvarchar](4000) NULL,
	[VIDEO_SEASON_ID] [nvarchar](4000) NULL,
	[VIDEO_RELEASE_YEAR] [nvarchar](4) NULL,
	[VIDEO_RATING] [nvarchar](6) NULL,
	[VIDEO_RATING_DESC] [nvarchar](4000) NULL,
	[VIDEO_SHORT_DESCRIPTION] [nvarchar](4000) NULL,
	[VIDEO_LONG_DESCRIPTION] [nvarchar](4000) NULL,
	[ASPECT_RATIO] [nvarchar](6) NULL,
	[ASPECT_RATIO_DESC] [nvarchar](4000) NULL,
	[MOVIE_RATING] [nvarchar](6) NULL,
	[MOVIE_RATING_DESC] [nvarchar](4000) NULL,
	[RATING_REASON] [nvarchar](4000) NULL,
	[ORIGINAL_CATALOG_NUMBER] [nvarchar](4000) NULL,
	[PREVIEW_START_TIME] [numeric](38, 0) NULL,
	[FORMATTED_PREVIEW_START_TIME] [nvarchar](4000) NULL,
	[PREVIEW_START_TIME_FRACTION] [numeric](3, 0) NULL,
	[PREVIEW_STOP_TIME] [numeric](38, 0) NULL,
	[FORMATTED_PREVIEW_STOP_TIME] [nvarchar](4000) NULL,
	[PREVIEW_STOP_TIME_FRACTION] [numeric](3, 0) NULL,
	[RESOURCE_COMPANY_LINK_ID] [numeric](38, 0) NOT NULL,
	[COUNTRY_ID] [nvarchar](2) NOT NULL,
	[FAMILY_ID] [nvarchar](6) NULL,
	[COMPANY_ID] [nvarchar](6) NOT NULL,
	[DIVISION_ID] [nvarchar](6) NOT NULL,
	[LABEL_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_COUNTRY_ID] [nvarchar](2) NOT NULL,
	[ORIGINATING_FAMILY_ID] [nvarchar](6) NULL,
	[ORIGINATING_COMPANY_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_DIVISION_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_LABEL_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_INDICATOR] [nvarchar](1) NOT NULL,
	[DQ_STATUS] [nvarchar](6) NOT NULL,
	[DQ_STATUS_DESC] [nvarchar](4000) NULL,
	[RIGHTS_TYPE] [nvarchar](6) NULL,
	[RIGHTS_TYPE_DESC] [nvarchar](4000) NULL,
	[RIGHTS_OWNER_ID] [numeric](38, 0) NULL,
	[RIGHTS_OWNER_DESC] [nvarchar](4000) NULL,
	[GENRE] [nvarchar](6) NULL,
	[GENRE_DESC] [nvarchar](4000) NULL,
	[LOCAL_NOTES] [nvarchar](4000) NULL,
	[CHANGE_CODE] [varchar](2) NOT NULL,
	[CHANGE_DATE_TIME] [datetime] NULL,
	[WORKFLOW_CODE] [varchar](2) DEFAULT 'E' NOT NULL
) ON [PRIMARY]
