CREATE TABLE [R2].[ResourceLocal](
	[RESOURCE_ID] [numeric](38, 0) NOT NULL,
	[ACCOUNT_ID] [numeric](38, 0) NOT NULL,
	[ISRC] [nvarchar](12) NULL,
	[ARTIST_LIST] [nvarchar](max) NULL,
	[RESOURCE_LOCAL_ID] [numeric](38, 0) NOT NULL,
	[TITLE] [nvarchar](max) NULL,
	[TITLE_OVERRIDE] [nvarchar](max) NULL,
	[VERSION_TITLE] [nvarchar](max) NULL,
	[VERSION_TITLE_OVERRIDE] [nvarchar](max) NULL,
	[TITLE_EXTENSION] [nvarchar](max) NULL,
	[TITLE_EXTENSION_OVERRIDE] [nvarchar](max) NULL,
	[FORMATTED_TITLE] [nvarchar](max) NULL,
	[ARTIST_OVERRIDE] [nvarchar](max) NULL,
	[PC_NOTICE_YEAR] [nvarchar](4) NULL,
	[PC_NOTICE_COMPANY_ID] [numeric](38, 0) NULL,
	[PC_NOTICE_COMPANY_NAME] [nvarchar](max) NULL,
	[PC_NOTICE_EXTENSION] [nvarchar](max) NULL,
	[FORMATTED_PC_NOTICE] [nvarchar](max) NULL,
	[VERSION_TYPE] [nvarchar](6) NULL,
	[VERSION_TYPE_DESC] [nvarchar](max) NULL,
	[E_MARKETING_TAG] [nvarchar](max) NULL,
	[E_RELEASE_LABEL] [nvarchar](max) NULL,
	[E_OWNING_LABEL] [nvarchar](max) NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[VIDEO_NETWORK] [nvarchar](6) NULL,
	[VIDEO_NETWORK_DESC] [nvarchar](max) NULL,
	[VIDEO_SEASON_ID] [nvarchar](max) NULL,
	[VIDEO_RELEASE_YEAR] [nvarchar](4) NULL,
	[VIDEO_RATING] [nvarchar](6) NULL,
	[VIDEO_RATING_DESC] [nvarchar](max) NULL,
	[VIDEO_SHORT_DESCRIPTION] [nvarchar](max) NULL,
	[VIDEO_LONG_DESCRIPTION] [nvarchar](max) NULL,
	[ASPECT_RATIO] [nvarchar](6) NULL,
	[ASPECT_RATIO_DESC] [nvarchar](max) NULL,
	[MOVIE_RATING] [nvarchar](6) NULL,
	[MOVIE_RATING_DESC] [nvarchar](max) NULL,
	[RATING_REASON] [nvarchar](max) NULL,
	[ORIGINAL_CATALOG_NUMBER] [nvarchar](max) NULL,
	[PREVIEW_START_TIME] [numeric](38, 0) NULL,
	[FORMATTED_PREVIEW_START_TIME] [nvarchar](max) NULL,
	[PREVIEW_START_TIME_FRACTION] [numeric](3, 0) NULL,
	[PREVIEW_STOP_TIME] [numeric](38, 0) NULL,
	[FORMATTED_PREVIEW_STOP_TIME] [nvarchar](max) NULL,
	[PREVIEW_STOP_TIME_FRACTION] [numeric](3, 0) NULL,
	[RESOURCE_COMPANY_LINK_ID] [numeric](38, 0) NOT NULL,
	[COUNTRY_ID] [nvarchar](2) NOT NULL,
	[FAMILY_ID] [nvarchar](6) NULL,
	[COMPANY_ID] [nvarchar](6) NOT NULL,
	[DIVISION_ID] [nvarchar](6) NOT NULL,
	[LABEL_ID] [nvarchar](6) NOT NULL,
	[ORIGINATING_INDICATOR] [nvarchar](1) NOT NULL,
	[DQ_STATUS] [nvarchar](6) NOT NULL,
	[RIGHTS_TYPE] [nvarchar](6) NULL,
	[RIGHTS_TYPE_DESC] [nvarchar](max) NULL,
	[RIGHTS_OWNER_ID] [numeric](38, 0) NULL,
	[RIGHTS_OWNER_DESC] [nvarchar](max) NULL,
	[GENRE] [nvarchar](6) NULL,
	[GENRE_DESC] [nvarchar](max) NULL,
	[LOCAL_NOTES] [nvarchar](max) NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'I' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) NOT NULL DEFAULT ('L')
) ON [PRIMARY]