CREATE TABLE [CRA].[LoadRecordingContract](
	[LOAD_RECORDING_CONTRACT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CRRE_ID] [bigint] NULL,
	[GTA_COMPANY_ID] [nvarchar](10) NULL,
	[CONTRIBUTOR_ID] [bigint] NULL,
	[CREATION_DATETIME] [datetime] NULL,
	[CRCR_NO_RIGHTS_IND] [char](1) NULL,
	[CRCR_NO_MASTER_IND] [char](1) NULL,
	[CRCR_NO_MULTI_ARTIST_IND] [char](1) NULL,
	[RMS_ID] [bigint] NULL,
	[ISRC] [nvarchar](20) NULL,
 CONSTRAINT [PK_LoadRecordingContract] PRIMARY KEY CLUSTERED 
(
	[LOAD_RECORDING_CONTRACT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]