CREATE TABLE DRA.ReleaseClearanceWorkflow
(
	RELEASE_ID numeric(38, 0) NOT NULL,
	STATUS_ID numeric(38, 0) NOT NULL,
	STATUS_TIMESTAMP datetime NOT NULL,
	EXTSYS_STATUS_ID numeric(38, 0) NULL,
	EXTSYS_STATUS_TIMESTAMP datetime NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'I' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) NOT NULL DEFAULT ('L')
);
