CREATE TABLE [DRA].[LoadEntityRejectionReason]
(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ENTITY_CLEARANCE_ID] [numeric](38, 0) NOT NULL,
	[REJECTION_REASON_ID] [numeric](38, 0) NOT NULL,
	[CHANGE_CODE] [varchar](2) DEFAULT 'C' NOT NULL,
	[CHANGE_DATE_TIME] [datetime] DEFAULT GETDATE() NOT NULL,
	[WORKFLOW_CODE] [varchar](2) DEFAULT 'E' NOT NULL
) ON [PRIMARY]
