//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace ReceiptSite.Models
{
    public partial class ReceiptsEntities : DbContext
    {
        public ReceiptsEntities()
            : base("name=ReceiptsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ImageBank> ImageBanks { get; set; }
        public DbSet<Receipt> Receipts { get; set; }
    }
}
