-- ============================================
-- Description:	Inserts records in R2.Resource
-- =============================================
CREATE PROCEDURE [R2].[ResourceLoadInsert] 
AS
BEGIN
	insert into R2.Resource
	select 
		[RESOURCE_ID] = l.[RESOURCE_ID]
		,[ACCOUNT_ID] = l.[ACCOUNT_ID]
		,[ISRC] = l.[ISRC]
		,[RESOURCE_TYPE] = l.[RESOURCE_TYPE]
		,[RESOURCE_TYPE_DESC] = l.[RESOURCE_TYPE_DESC]
		,[ORIGINAL_PROJECT_ID] = l.[ORIGINAL_PROJECT_ID]
		,[TIME] = l.[TIME]
		,[FORMATTED_TIME] = l.[FORMATTED_TIME]
		,[MUSIC_TYPE] = l.[MUSIC_TYPE]
		,[MUSIC_TYPE_DESC] = l.[MUSIC_TYPE_DESC]
		,[LANGUAGE_NO] = l.[LANGUAGE_NO]
		,[LANGUAGE_DESC] = l.[LANGUAGE_DESC]
		,[MISCELLANEOUS_CREDITS] = l.[MISCELLANEOUS_CREDITS]
		,[SAMPLE_CREDITS] = l.[SAMPLE_CREDITS]
		,[TECHNICAL_FORMAT] = l.[TECHNICAL_FORMAT]
		,[TECHNICAL_FORMAT_DESC] = l.[TECHNICAL_FORMAT_DESC]
		,[ANALOG_DIGITAL_CODE] = l.[ANALOG_DIGITAL_CODE]
		,[ANALOG_DIGITAL_CODE_DESC] = l.[ANALOG_DIGITAL_CODE_DESC]
		,[SAMPLING_FREQUENCY] = l.[SAMPLING_FREQUENCY]
		,[SAMPLING_FREQUENCY_DESC] = l.[SAMPLING_FREQUENCY_DESC]
		,[BIT_DEPTH] = l.[BIT_DEPTH]
		,[BIT_DEPTH_DESC] = l.[BIT_DEPTH_DESC]
		,[SCORE_PUBLISHER_ID] = l.[SCORE_PUBLISHER_ID]
		,[SCORE_PUBLISHER_DESC] = l.[SCORE_PUBLISHER_DESC]
		,[SEARCH_INFORMATION] = l.[SEARCH_INFORMATION]
		,[SESSION_NAME] = l.[SESSION_NAME]
		,[SESSION_COUNTRY_ID] = l.[SESSION_COUNTRY_ID]
		,[SESSION_LOCATION_ID] = l.[SESSION_LOCATION_ID]
		,[SESSION_LOCATION_DESC] = l.[SESSION_LOCATION_DESC]
		,[SESSION_SETTING] = l.[SESSION_SETTING]
		,[SESSION_SETTING_DESC] = l.[SESSION_SETTING_DESC]
		,[SESSION_UNION_TYPE] = l.[SESSION_UNION_TYPE]
		,[SESSION_UNION_TYPE_DESC] = l.[SESSION_UNION_TYPE_DESC]
		,[SESSION_PERFORMANCE_TYPE] = l.[SESSION_PERFORMANCE_TYPE]
		,[SESSION_PERFORMANCE_TYPE_DESC] = l.[SESSION_PERFORMANCE_TYPE_DESC]
		,[SESSION_START_DATE_YEAR] = l.[SESSION_START_DATE_YEAR]
		,[SESSION_START_DATE_MONTH] = l.[SESSION_START_DATE_MONTH]
		,[SESSION_START_DATE_DAY] = l.[SESSION_START_DATE_DAY]
		,[SESSION_START_DATE] = l.[SESSION_START_DATE]
		,[SESSION_END_DATE_YEAR] = l.[SESSION_END_DATE_YEAR]
		,[SESSION_END_DATE_MONTH] = l.[SESSION_END_DATE_MONTH]
		,[SESSION_END_DATE_DAY] = l.[SESSION_END_DATE_DAY]
		,[SESSION_END_DATE] = l.[SESSION_END_DATE]
		,[ORIGINAL_MATRIX_NUMBER] = l.[ORIGINAL_MATRIX_NUMBER]
		,[MASTERING_TRACK_COUNT] = l.[MASTERING_TRACK_COUNT]
		,[CATEGORY] = l.[CATEGORY]
		,[CATEGORY_DESC] = l.[CATEGORY_DESC]
		,[FORMAT] = l.[FORMAT]
		,[FORMAT_DESC] = l.[FORMAT_DESC]
		,[COLOR_MODE] = l.[COLOR_MODE]
		,[COLOR_MODE_DESC] = l.[COLOR_MODE_DESC]
		,[RESOLUTION] = l.[RESOLUTION]
		,[RESOLUTION_DESC] = l.[RESOLUTION_DESC]
		,[MEASUREMENT] = l.[MEASUREMENT]
		,[MEASUREMENT_DESC] = l.[MEASUREMENT_DESC]
		,[HEIGHT] = l.[HEIGHT]
		,[WIDTH] = l.[WIDTH]
		,[VIDEO_TYPE] = l.[VIDEO_TYPE]
		,[VIDEO_TYPE_DESC] = l.[VIDEO_TYPE_DESC]
		,[VIDEO_PRODUCTION_NUMBER] = l.[VIDEO_PRODUCTION_NUMBER]
		,[NOTES] = l.[NOTES]
		,[ISAN] = l.[ISAN]
		,[AVAILABLE_INDICATOR] = l.[AVAILABLE_INDICATOR]
		,[ORIGINATING_COUNTRY_ID] = l.[ORIGINATING_COUNTRY_ID]
		,[ORIGINATING_FAMILY_ID] = l.[ORIGINATING_FAMILY_ID]
		,[ORIGINATING_COMPANY_ID] = l.[ORIGINATING_COMPANY_ID]
		,[ORIGINATING_DIVISION_ID] = l.[ORIGINATING_DIVISION_ID]
		,[ORIGINATING_LABEL_ID] = l.[ORIGINATING_LABEL_ID]
		
		,CHANGE_CODE = ld.CHANGE_CODE 
		,CHANGE_DATE_TIME = getdate()
		,WORKFLOW_CODE = 'L'
	from 
		R2.LoadResource l 
		inner join R2.LoadResourceDriver ld 
			on l.[RESOURCE_ID] = ld.[RESOURCE_ID]
	where 
		(ld.CHANGE_CODE = 'I' or ld.CHANGE_CODE = 'ID') and ld.[WORKFLOW_CODE] = 'T'
		and
		l.[WORKFLOW_CODE] = 'LT' 
		
	-- update row counts		
	exec R2.TransformLogTaskInsert 'R2.Resource', @@rowcount, 'I'
		
END
