-- ============================================
-- Description:	Inserts records in R2.ReleaseLocal
-- =============================================
CREATE PROCEDURE [R2].[ReleaseLoadInsertLocal] 
AS
BEGIN
	insert into R2.ReleaseLocal
	select 
		[RELEASE_ID] = l.[RELEASE_ID]
		,[ACCOUNT_ID] = l.[ACCOUNT_ID]
		,[UPC] = l.[UPC]
		,[ARTIST_LIST] = l.[ARTIST_LIST]
		,[RELEASE_LOCAL_ID] = l.[RELEASE_LOCAL_ID]
		,[TITLE] = l.[TITLE]
		,[TITLE_OVERRIDE] = l.[TITLE_OVERRIDE]
		,[VERSION_TITLE] = l.[VERSION_TITLE]
		,[VERSION_TITLE_OVERRIDE] = l.[VERSION_TITLE_OVERRIDE]
		,[FORMATTED_TITLE] = l.[FORMATTED_TITLE]
		,[ARTIST_OVERRIDE] = l.[ARTIST_OVERRIDE]
		,[VERSION_TYPE] = l.[VERSION_TYPE]
		,[VERSION_TYPE_DESC] = l.[VERSION_TYPE_DESC]
		,[P_NOTICE_YEAR] = l.[P_NOTICE_YEAR]
		,[P_NOTICE_COMPANY_ID] = l.[P_NOTICE_COMPANY_ID]
		,[P_NOTICE_COMPANY_NAME] = l.[P_NOTICE_COMPANY_NAME]
		,[P_NOTICE_EXTENSION] = l.[P_NOTICE_EXTENSION]
		,[FORMATTED_P_NOTICE] = l.[FORMATTED_P_NOTICE]
		,[C_NOTICE_YEAR] = l.[C_NOTICE_YEAR]
		,[C_NOTICE_COMPANY_ID] = l.[C_NOTICE_COMPANY_ID]
		,[C_NOTICE_COMPANY_NAME] = l.[C_NOTICE_COMPANY_NAME]
		,[FORMATTED_C_NOTICE] = l.[FORMATTED_C_NOTICE]
		,[SERIES_ID] = l.[SERIES_ID]
		,[SERIES_TITLE] = l.[SERIES_TITLE]
		,[VIDEO_NETWORK] = l.[VIDEO_NETWORK]
		,[VIDEO_NETWORK_DESC] = l.[VIDEO_NETWORK_DESC]
		,[VIDEO_SEASON_ID] = l.[VIDEO_SEASON_ID]
		,[VIDEO_ORIGINAL_RELEASE_YEAR] = l.[VIDEO_ORIGINAL_RELEASE_YEAR]
		,[VIDEO_RATING] = l.[VIDEO_RATING]
		,[VIDEO_RATING_DESC] = l.[VIDEO_RATING_DESC]
		,[VIDEO_SHORT_DESCRIPTION] = l.[VIDEO_SHORT_DESCRIPTION]
		,[VIDEO_LONG_DESCRIPTION] = l.[VIDEO_LONG_DESCRIPTION]
		,[E_MARKETING_TAG] = l.[E_MARKETING_TAG]
		,[E_RELEASE_LABEL] = l.[E_RELEASE_LABEL]
		,[NPSC] = l.[NPSC]
		,[VOD_TYPE] = l.[VOD_TYPE]
		,[VOD_TYPE_DESC] = l.[VOD_TYPE_DESC]
		,[RELEASE_COMPANY_LINK_ID] = l.[RELEASE_COMPANY_LINK_ID]
		,[COUNTRY_ID] = l.[COUNTRY_ID]
		,[FAMILY_ID] = l.[FAMILY_ID]
		,[COMPANY_ID] = l.[COMPANY_ID]
		,[DIVISION_ID] = l.[DIVISION_ID]
		,[LABEL_ID] = l.[LABEL_ID]
		,[ORIGINATING_INDICATOR] = l.[ORIGINATING_INDICATOR]
		,[STATUS] = l.[STATUS]
		,[STATUS_DESC] = l.[STATUS_DESC]
		,[ISSUING_EMPLOYEE_NO] = l.[ISSUING_EMPLOYEE_NO]
		,[ISSUING_EMPLOYEE_NAME] = l.[ISSUING_EMPLOYEE_NAME]
		,[ROYALTY_ADMIN] = l.[ROYALTY_ADMIN]
		,[ROYALTY_ADMIN_DESC] = l.[ROYALTY_ADMIN_DESC]
		,[CATALOG_NUMBER] = l.[CATALOG_NUMBER]
		,[GENRE] = l.[GENRE]
		,[GENRE_DESC] = l.[GENRE_DESC]
		,[RELEASE_DATE_YEAR] = l.[RELEASE_DATE_YEAR]
		,[RELEASE_DATE_MONTH] = l.[RELEASE_DATE_MONTH]
		,[RELEASE_DATE_DAY] = l.[RELEASE_DATE_DAY]
		,[RELEASE_DATE_DISPLAY] = l.[RELEASE_DATE_DISPLAY]
		,[LOCAL_NOTES] = l.[LOCAL_NOTES]
		,[DQ_STATUS] = l.[DQ_STATUS]
		,[DQ_STATUS_DESC] = l.[DQ_STATUS_DESC]
		
		,CHANGE_CODE = ld.CHANGE_CODE 
		,CHANGE_DATE_TIME = getdate()
		,WORKFLOW_CODE = 'L'
	from 
		R2.LoadReleaseLocal l 
		inner join R2.LoadReleaseLocalDriver ld 
			on l.[RELEASE_ID] = ld.[RELEASE_ID] and l.[COMPANY_ID] = ld.[COMPANY_ID]
	where 
		(ld.CHANGE_CODE = 'I' or ld.CHANGE_CODE = 'ID') and ld.[WORKFLOW_CODE] = 'T'
		and
		l.[WORKFLOW_CODE] = 'LT' 
		
	-- update row counts		
	exec R2.TransformLogTaskInsert 'R2.ReleaseLocal', @@rowcount, 'I'
		
END
