<?xml version="1.0" encoding="utf-8"?><Database Name="RDxETL" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=USHPEPVSQL409\USHPEPVSQL409;Initial Catalog=RDxETL;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RDxETLConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Box" Member="Boxes">
    <Type Name="Box">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="app" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="env" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fishers" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="tulsa" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="app_dirs" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="conn_to" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Job" Member="Jobs">
    <Type Name="Job">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="time" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="freq" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="cmd" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="result" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Issue" Member="Issues">
    <Type Name="Issue">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IssueView" Member="IssueViews">
    <Type Name="IssueView">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>